export const CONTENTNAME = '/inmanage'
export const HOME_PATH = 'home'
export const HOME_MENU = ''
export const HOME_ITEM = ''
export const REMOTE_URL = 'http://' + window.location.host + '/inmanage'
export const CHECKCODE_URL = 'http://139.224.128.69:8060/inmanage'
export const TASKMAN_LOG_PORT = 'ws://192.168.2.106:8887'