import {CONTENTNAME,REMOTE_URL,CHECKCODE_URL} from './contants';
module.exports = {
	API: {
		CONTENTNAME: CONTENTNAME,
		//廖伟民--机构的接口
		CHECKCODE_URL:CHECKCODE_URL + '/IM01003.do',
		LOGIN_URL: REMOTE_URL + '/IM01001.do',
		SESSION_URL: REMOTE_URL + '/IM01005.do',
		GET_BRANCH_URL_BYID: REMOTE_URL + '/IM02005.do',//
		GET_BRANCH_LIST_URL: REMOTE_URL + '/IM02004.do',
		GET_BRANCH_DELETE: REMOTE_URL + '/IM02002.do',
		GET_BRANCH_ADD: REMOTE_URL + '/IM02001.do',
		GET_BRANCH_MODIFY: REMOTE_URL + '/IM02003.do',

		//廖伟民--岗位的接口
		GET_POST_LIST_URL:REMOTE_URL + '/IM02006.do',
		GET_POST_ALL_LIST_URL:REMOTE_URL + '/IM02009.do',
		GET_QUERY_POST_LIST_URL:REMOTE_URL + '/IM02010.do',
		MODIFY_QUERY_POST_LIST_URL:REMOTE_URL + '/IM02007.do',//修改 
		DELTE_POST_LIST_URL:REMOTE_URL + '/IM02008.do',//删除

		AUTHRESOURCE_URL: REMOTE_URL + '/IM01006.do',
		USERINFO_URL: REMOTE_URL + '/IM01006.do',

		GET_FUNCTIONlIST_URL: REMOTE_URL + '/IM06004.do',
		ADD_FUNCTIONITEM_URL: REMOTE_URL + '/IM06001.do',
		DEL_FUNCTIONITEM_URL: REMOTE_URL + '/IM06003.do',
		MOD_FUNCTIONITEM_URL: REMOTE_URL + '/IM06002.do',
		GET_FUNCTIONITEM_URL: REMOTE_URL + '/IM06005.do',

		USER_PAGE_BY_BRH_URL: REMOTE_URL + '/IM03004.do',

		GET_CONFIG_DATA_URL: REMOTE_URL + '/IM01002.do',
		GET_ROLE_LIST_URL: REMOTE_URL + '/IM05003.do',

		USER_ADD_URL: REMOTE_URL + '/IM09004.do',
		USER_BIND_ROLE_URL: REMOTE_URL + '/IM03005.do',
		USER_DEL_URL: REMOTE_URL + '/IM03001.do',

		GET_ROLE_BY_USER_URL: REMOTE_URL + '/IM03003.do',
		
		USER_UPDATE_URL: REMOTE_URL + '/IM03002.do',
		USER_DEL_ROLE_URL: REMOTE_URL + '/UserReverseRoleAction.do',

		GET_ROLE_BY_NAME_URL: REMOTE_URL + '/RoleGetByNameAction.do',
		////.................
		GET_ITEM_BY_ROLE_URL: REMOTE_URL + '/IM05004.do',//角色详情
		////.................
		ROLE_UPDATE_URL: REMOTE_URL + '/IM05002.do',
		ROLE_NAME_CHK_URL: REMOTE_URL + '/IM05004.do',
		ROLE_ADD_URL: REMOTE_URL + '/IM09005.do',
		ROLE_DEL_URL: REMOTE_URL + '/IM05001.do',

		GET_ALL_ITEM_PAGE_URL: REMOTE_URL + '/IM05005.do',

		ROLE_BIND_ITEM_URL: REMOTE_URL + '/IM05006.do',

		GET_MENU_LIST_URL: REMOTE_URL + '/IM07005.do',
		MENU_ITEM_DEL_URL: REMOTE_URL + '/IM07008.do',
		GET_ITEM_BY_MENU_URL: REMOTE_URL + '/IM07009.do',
		GET_MENU_URL: REMOTE_URL + '/IM07004.do',

		GET_ABS_ITEM_PAGE_URL: REMOTE_URL + '/IM07010.do',

		ADD_MENU_ITEM_URL: REMOTE_URL + '/IM07006.do',
		UPDATE_MENU_URL: REMOTE_URL + '/IM07002.do',
		UPDATE_MENU_ITEM_URL: REMOTE_URL + '/IM07007.do',

		GET_ALL_FIRST_PAGE_URL:REMOTE_URL+ '/IM05007.do',
		CONNET_USER_AND_ROLE_URL:REMOTE_URL+ '/IM09006.do',

		//李梓铭-策略管理
		GET_STRATEGY_LIST_URL:REMOTE_URL+ '/IM04005.do',
		ADD_STRATEGY_URL:REMOTE_URL+ '/IM04001.do',
		DELETE_STRATEGY_URL:REMOTE_URL+ '/IM04003.do',
		EDIT_STRATEGY_URL:REMOTE_URL+ '/IM04002.do',
		GET_STRATEGY_URL:REMOTE_URL+ '/IM04004.do',
		GET_BSN_LIST_URL:REMOTE_URL+ '/IM08005.do',
		SET_CONNECTION_URL:REMOTE_URL+ '/IM08007.do',

		//李梓铭-审查管理
		GET_CHECK_LIST_URL:REMOTE_URL+ '/IM09002.do',
		GET_CHECK_HISTORY_LIST_URL:REMOTE_URL+ '/IM09001.do',
		OPERATE_CHECK_URL:REMOTE_URL+ '/IM09003.do',
		GET_STATE_LIST_URL:REMOTE_URL+ '/IM09007.do',

		//注销
		LOGOUT_URL:REMOTE_URL+'/IM01004.do',
		//修改密码
		CHANGE_PASSWORD_URL:REMOTE_URL+'/IM03006.do',

		//饶浪君-TASKMAN
		GET_SCHEDULE_LIST:REMOTE_URL+'/TSM01001.do',
		OPERATE_SCHEDULE:REMOTE_URL+'/TSM01018.do',
		ADD_SCHEDULE:REMOTE_URL+'/TSM01002.do',
		SAVE_SCHEDULE:REMOTE_URL+'/TSM01003.do',
		DEL_SCHEDULE:REMOTE_URL+'/TSM01004.do',
		SCHEDULE_REL_TASK:REMOTE_URL+'/TSM01014.do',
		SAVE_SCHEDULE_TASK_REL:REMOTE_URL+'/TSM01013.do',

		//廖伟民--TASKMAN普通任务
		GET_TASK_LIST_URL:REMOTE_URL+'/TSM01008.do',
		ADD_TASK_LIST_URL:REMOTE_URL+'/TSM01005.do',
		MODIFY_TASK_LIST_URL:REMOTE_URL+'/TSM01006.do',
		DELETE_TASK_LIST_URL:REMOTE_URL+'/TSM01007.do',
		//廖伟民--TASKMAN批量任务
		GET_BATCH_TASK_LIST_URL:REMOTE_URL+'/TSM01012.do',
		ADD_BATCH_TASK_LIST_URL:REMOTE_URL+'/TSM01009.do',
		DETAIL_BATCH_TASK_LIST_URL:REMOTE_URL+'/TSM01016.do',
		MODIFY_BATCH_TASK_LIST_URL:REMOTE_URL+'/TSM01011.do',
		DELETE_BATCH_TASK_LIST_URL:REMOTE_URL+'/TSM01010.do',

		//廖伟民计划权限管理
		GET_ASSOCIATE_LIST_URL:REMOTE_URL+'/TSM01017.do',
		DO_SCHEDULE_ROLE_ASSOCIATE_URL:REMOTE_URL+'/TSM01015.do',

	}
}
