export const AUTH_MENU_REQ = 'AUTH_MENU_REQ'  
export const AUTH_MENU_SUC = 'AUTH_MENU_SUC'  
export const AUTH_MENU_FAL = 'AUTH_MENU_FAL'  
export const CHANGE_TOP_MENU = 'CHANGE_TOP_MENU'  
export const SELECT_LEFT_MENU = 'SELECT_LEFT_MENU'  
export const SELECT_LEFT_P_MENU  =  'SELECT_LEFT_P_MENU'  
export const USER_MENU_REQ = 'USER_MENU_REQ'  
export const USER_MENU_SUC = 'USER_MENU_SUC'  
export const USER_MENU_FAL = 'USER_MENU_FAL'  
export const MERGE_TOP_MENU  =  'MERGE_TOP_MENU'  
export const SYSTEM_PARAM = 'SYSTEM_PARAM'  
export const APP_LIST_REQ = 'APP_LIST_REQ'  
export const APP_LIST_SUC = 'APP_LIST_SUC'  
export const APP_LIST_FAL = 'APP_LIST_FAL'  

export const CHANGE_QUERY_ITEM  =  'CHANGE_QUERY_ITEM'  
export const MERGE_FINAL_MENU = 'MERGE_FINAL_MENU'  

export const SET_BUGFREE_MENU = 'SET_BUGFREE_MENU'  

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'  
export const SAVE_USER_MENU  =  'SAVE_USER_MENU'

export const USER_GROUP_BRANCH  =  'USER_GROUP_BRANCH'
export const UPDATE_BRANACH  =  'UPDATE_BRANACH'

export const SENDDATA  =  'SENDDATA'  

export const GET_BRANCH_LIST  =  'GET_BRANCH_LIST'  
export const GET_BRANCH_LIST_REQ  =  'GET_BRANCH_LIST_REQ'  
export const GET_BRANCH_LIST_SUC  =  'GET_BRANCH_LIST_SUC'  
export const GET_BRANCH_LIST_FAL  =  'GET_BRANCH_LIST_FAL'  

export const CLEAN_BRANCH  =  'CLEAN_BRANCH'

export const CONFIG_DATA_REQ = 'CONFIG_DATA_REQ'
export const CONFIG_DATA_SUC = 'CONFIG_DATA_SUC'
export const CONFIG_DATA_FAL = 'CONFIG_DATA_FAL'

export const ROLE_QUERY_REQ = 'ROLE_QUERY_REQ'
export const ROLE_QUERY_SUC = 'ROLE_QUERY_SUC'
export const ROLE_QUERY_FAL = 'ROLE_QUERY_FAL'

export const ROLE_TREE_LIST = 'ROLE_TREE_LIST'
export const UPDATE_ROLE_TREE = 'UPDATE_ROLE_TREE'

export const SET_USER_TYPE_LEVEL = 'SET_USER_TYPE_LEVEL'  